sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
env:
  global:
    - BUILD_TIMEOUT=10000
install: npm install --ignore-scripts
before_install:
  - if [[ $TRAVIS_NODE_VERSION -lt 8 ]]; then npm install --global npm@5; fi
# script: npm run ci
