sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
env:
  global:
    - BUILD_TIMEOUT=10000
install: npm ci --ignore-scripts
before_install:
  - if [[ $TRAVIS_NODE_VERSION -lt 6 ]]; then npm install --global npm@5; else npm install --global npm@latest; fi
script: npm run ci
