[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
swc = "0.266.36"
swc_common = "0.32.1"
swc_ecma_ast = "0.109.1"
swc_ecma_parser = "0.140.0"
swc_error_reporters = "0.16.1"
parking_lot = "0.12.1"
swc_ecma_lints = "0.88.7"
swc_ecma_transforms_base = "0.133.6"
swc_ecma_visit = "0.95.1"
