[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
swc = "0.265.7"
swc_common = "0.32.0"
swc_ecma_ast = "0.109.0"
swc_ecma_parser = "0.139.0"
swc_error_reporters = "0.16.0"
parking_lot = "0.12.1"
swc_ecma_lints = "0.87.2"
swc_ecma_transforms_base = "0.132.2"
swc_ecma_visit = "0.95.0"
