version: 2

jobs:
  analysis:
    docker:
      - image: rollupcabal/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm ci --ignore-scripts
      - run:
          name: Running linting
          command: npm run ci:lint
      - run:
          name: Running NPM Security Audit
          command: npm run security
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  node-v10-latest:
    docker:
      - image: rollupcabal/circleci-node-v10:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Running tests
          command: npm run ci:test
      - store_artifacts:
          name: Storing browser build for REPL
          path: /home/circleci/project/dist/rollup.browser.js
          destination: rollup.browser.js
      - run:
          name: Post REPL comment
          command: ./scripts/post-comment.js
  node-v12-latest:
    docker:
      - image: rollupcabal/circleci-node-v12:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Running tests with coverage
          command: npm run ci:coverage


workflows:
  version: 2
  validate-test:
    jobs:
      - analysis:
          filters:
            tags:
              only: /.*/
      - node-v10-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
      - node-v12-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
