name: update-contributors-svg

on:
  # Schedule the interval of the checks.
  schedule:
    - cron: '0 7 * * *' # Everyday 7:00

jobs:
  update-svg:
    name: Update contributors SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: npx pnpm i

      - name: Run SVG generation script
        run: npx gh-contrib-svg -t ${{ secrets.GITHUB_TOKEN }} -o rollup -r rollup-docs-cn

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: "chore(workflow): update contributors image"
          add: ".github-contributors/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}